### ISSUE TITLE
组合模式貌似没有

### ISSUE THREAD

**Issue by Heyjoy** [me115/design_patterns#14]
受益匪浅。
阅读过程中发现结构型模式中提到的“组合模式”重要度比较高却没有提到，
是否有何考量？
谢谢！

**Comment by HelenXR** [comment]
原型模式也没有,在目录里有列出来,但是说明.
朋友,你也在学习设计模式么?我加你一下可以么.

**Comment by me115** [comment]
嗯, 不是所有的模式都写了；大家如果有兴趣，可总结后写出来了，merger进来； @Heyjoy @HelenXR
