### ISSUE TITLE
应该是序列图，而不是时序图

### ISSUE THREAD

**Issue by woshihoujinxin** [me115/design_patterns#8]

**Comment by me115** [comment]
时序图（Sequence Diagram），亦称为序列图或循序图，是一种UML行为图。它通过描述对象之间发送消息的时间顺序显示多个对象之间的动态协作。它可以表示用例的行为顺序，当执行一个用例行为时，时序图中的每条消息对应了一个类操作或状态机中引起转换的触发事件。[1]

https://zh.wikipedia.org/wiki/%E6%97%B6%E5%BA%8F%E5%9B%BE

**Comment by woshihoujinxin** [comment]
只能说这个维基写的不准确，我查遍了各种词典也没发现Sequence有时间的意思，而且UML规范里对时序图的描述也没有提到时间的这个词。所以我把上面wiki的内容修改掉了

**Comment by runME** [comment]
约定俗成吧,好多地方都叫时序图,Sequence本身是序列的意思,序列中每个操作还是有先后,有时间消耗,意译为时序,亦无不可.
